/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/notes/new` | `/notes/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/notes` | `/notes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/notes/new` | `/notes/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/notes${`?${string}` | `#${string}` | ''}` | `/notes${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/notes/new${`?${string}` | `#${string}` | ''}` | `/notes/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/notes/new` | `/notes/new`; params?: Router.UnknownInputParams; } | `${'/(authenticated)'}/notes/${Router.SingleRoutePart<T>}` | `/notes/${Router.SingleRoutePart<T>}` | { pathname: `${'/(authenticated)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
